import re
import sqlite3
from datetime import datetime, timezone
from pipeline.config import DB_PATH, VERTICALS

SCHEMA = "\nCREATE TABLE IF NOT EXISTS signals (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    source_name TEXT NOT NULL,\n    source_url TEXT,\n    signal_type TEXT NOT NULL,\n    title TEXT NOT NULL,\n    summary TEXT,\n    published_date TEXT,\n    collected_at TEXT NOT NULL,\n    vertical_hint TEXT,\n    UNIQUE(source_url, title)\n);\n\nCREATE TABLE IF NOT EXISTS opportunity_spaces (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    label TEXT UNIQUE,              -- e.g. \"OS001\" -- stays globally unique\n    run_id TEXT,                    -- which run registered/last touched this OS\n    vertical TEXT NOT NULL,\n    use_case TEXT NOT NULL,\n    technology TEXT NOT NULL,\n    persona TEXT,                   -- see config.ROLES (which Orange Business team owns this)\n    buyer_persona TEXT,             -- see config.BUYER_PERSONAS (who the customer-side contact is)\n    geography TEXT,                 -- see config.GEOS\n    horizon TEXT,                   -- Now / Next / Later, see config.HORIZONS\n    domain TEXT,                    -- see config.DOMAINS_TAXONOMY\n    next_action TEXT,               -- LLM-generated recommended next step\n    created_at TEXT NOT NULL,\n    last_refreshed TEXT\n);\n\nCREATE TABLE IF NOT EXISTS opportunity_signals (\n    opportunity_space_id INTEGER NOT NULL,\n    signal_id INTEGER NOT NULL,\n    PRIMARY KEY (opportunity_space_id, signal_id),\n    FOREIGN KEY (opportunity_space_id) REFERENCES opportunity_spaces(id),\n    FOREIGN KEY (signal_id) REFERENCES signals(id)\n);\n\nCREATE TABLE IF NOT EXISTS scores (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    opportunity_space_id INTEGER NOT NULL,\n    market_signal_strength REAL,\n    source_diversity REAL,\n    evidence_quality REAL,\n    evidence_quality_justification TEXT,\n    novelty_momentum REAL,\n    strategic_relevance REAL,\n    strategic_relevance_justification TEXT,\n    urgency_score REAL,             -- 0-10, time pressure from regulation/buying-signal density\n    total_score REAL,\n    computed_at TEXT NOT NULL,\n    FOREIGN KEY (opportunity_space_id) REFERENCES opportunity_spaces(id)\n);\n\nCREATE TABLE IF NOT EXISTS right_to_win_scores (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    opportunity_space_id INTEGER NOT NULL,\n    portfolio_distance TEXT,          -- L0 to L4, see config.PORTFOLIO_DISTANCE\n    right_to_win_score REAL,          -- 0-10, separate from attractiveness\n    matched_assets TEXT,              -- comma-separated Orange Business asset names cited\n    justification TEXT,\n    computed_at TEXT NOT NULL,\n    FOREIGN KEY (opportunity_space_id) REFERENCES opportunity_spaces(id)\n);\n\nCREATE TABLE IF NOT EXISTS watchlist_terms (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    term TEXT NOT NULL,               -- the candidate use_case or technology name\n    category TEXT NOT NULL,           -- 'use_case' or 'technology'\n    vertical TEXT,                    -- which vertical it showed up in\n    frequency INTEGER NOT NULL DEFAULT 1,\n    first_seen TEXT NOT NULL,\n    last_seen TEXT NOT NULL,\n    status TEXT NOT NULL DEFAULT 'pending',  -- pending / proposed / approved / rejected\n    UNIQUE(term, category, vertical)\n);\n\n-- Tracks VALID (in-taxonomy) Vertical x Use Case x Technology themes across\n-- successive analyze.py runs. Once frequency crosses\n-- config.RECURRING_THEME_PROMOTION_THRESHOLD, `radar_cli.py promote` turns\n-- it into a real opportunity space. See module docstring above for how\n-- this differs from watchlist_terms.\nCREATE TABLE IF NOT EXISTS recurring_themes (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    vertical TEXT NOT NULL,\n    use_case TEXT,\n    technology TEXT,\n    rationale TEXT,\n    supporting_signal_count INTEGER DEFAULT 0,\n    first_seen TEXT NOT NULL,\n    last_seen TEXT NOT NULL,\n    frequency INTEGER DEFAULT 1,\n    promoted INTEGER NOT NULL DEFAULT 0,   -- 0/1 -- already turned into an opportunity space?\n    run_id TEXT,\n    UNIQUE(vertical, use_case, technology)\n);\n\n-- Sieg 24/8 -- added to the central SCHEMA to match the diff, which\n-- declares this table here too, not only via extend_taxonomy.py's own\n-- init_proposals_table() (kept, called from radar_cli.py's cmd_review as a\n-- safety net -- both are CREATE TABLE IF NOT EXISTS, so having it in both\n-- places is harmless, just belt-and-suspenders: `python -m pipeline.db`\n-- alone is now enough to have this table ready, without needing\n-- extend_taxonomy.py to have run first).\n-- One row per proposed taxonomy term (use_case OR technology, never both),\n-- generated by extend_taxonomy.py from a watchlist_terms entry that\n-- crossed the frequency threshold. `radar_cli.py review` approves/rejects.\nCREATE TABLE IF NOT EXISTS proposals (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    vertical TEXT NOT NULL,\n    proposed_use_case TEXT,\n    proposed_technology TEXT,\n    frequency INTEGER NOT NULL,\n    first_seen TEXT NOT NULL,\n    last_seen TEXT NOT NULL,\n    status TEXT DEFAULT 'pending',\n    reviewed_at TEXT,\n    reviewed_by TEXT,\n    run_id TEXT,\n    UNIQUE(vertical, proposed_use_case, proposed_technology)\n);\n"


def get_connection():
    """One connection, with foreign keys enforced.

    SQLite leaves foreign keys OFF per connection unless asked, so the
    REFERENCES clauses in SCHEMA were documentation: a score could point at an
    opportunity space that no longer existed and nothing would say so. Every
    connection the pipeline opens goes through here, so this is the one place
    to turn them on. `repair_foreign_key_targets` has to run once first on a
    database whose child tables still reference a renamed parent.
    """
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


# The child tables whose FOREIGN KEY clauses can be left pointing at a table
# that no longer exists. `ALTER TABLE ... RENAME` rewrites the references other
# tables hold to the renamed table, so a migration that renamed
# opportunity_spaces to opportunity_spaces_old, recreated it and dropped the
# old one left all three children referencing "opportunity_spaces_old": every
# row then counts as a foreign-key violation while the ids themselves are fine.
_CHILD_TABLES = ("opportunity_signals", "scores", "right_to_win_scores")


def _dangling_fk_targets(conn, table):
    """The tables `table`'s FOREIGN KEY clauses name that do not exist."""
    row = conn.execute("SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone()
    if row is None:
        return []
    live = {r[0] for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    return [t for t in re.findall(r'REFERENCES\s+"?(\w+)"?', row[0]) if t not in live]


def repair_foreign_key_targets(conn):
    """Rebuild any child table whose foreign keys name a table that is gone.

    The rebuild is the standard SQLite one, since a FOREIGN KEY clause cannot be
    altered in place: rename the broken table aside, recreate it from SCHEMA
    (whose clauses name the live parent), copy the columns both versions share,
    drop the old one. Foreign keys are switched off for the duration because
    the rename itself would otherwise be refused, and `legacy_alter_table` is
    set so that the rename does not rewrite references yet again. Returns the
    tables rebuilt, and leaves `PRAGMA foreign_key_check` empty on a database
    whose rows were consistent all along, which is the case this was written
    for: no row is dropped or changed.
    """
    rebuilt = []
    for table in _CHILD_TABLES:
        if not _dangling_fk_targets(conn, table):
            continue
        conn.execute("PRAGMA foreign_keys = OFF")
        conn.execute("PRAGMA legacy_alter_table = ON")
        conn.execute(f"ALTER TABLE {table} RENAME TO {table}__broken")
        conn.executescript(SCHEMA)  # recreates `table` with the live parent
        old_cols = {r[1] for r in conn.execute(f"PRAGMA table_info({table}__broken)")}
        cols = ", ".join(r[1] for r in conn.execute(f"PRAGMA table_info({table})") if r[1] in old_cols)
        conn.execute(f"INSERT INTO {table} ({cols}) SELECT {cols} FROM {table}__broken")
        conn.execute(f"DROP TABLE {table}__broken")
        conn.commit()
        conn.execute("PRAGMA legacy_alter_table = OFF")
        conn.execute("PRAGMA foreign_keys = ON")
        rebuilt.append(table)
    return rebuilt


MIGRATIONS = [
    ("opportunity_spaces", "persona", "TEXT"),
    ("opportunity_spaces", "buyer_persona", "TEXT"),
    ("opportunity_spaces", "geography", "TEXT"),
    ("opportunity_spaces", "horizon", "TEXT"),
    ("opportunity_spaces", "next_action", "TEXT"),
    ("opportunity_spaces", "domain", "TEXT"),
    ("opportunity_spaces", "run_id", "TEXT"),
    ("scores", "urgency_score", "REAL"),
    ("recurring_themes", "promoted", "INTEGER NOT NULL DEFAULT 0"),
    ("opportunity_spaces", "next_action_strategist", "TEXT"),
    ("opportunity_spaces", "next_action_sales", "TEXT"),
    ("opportunity_spaces", "next_action_presales", "TEXT"),
]


def migrate_schema(conn):
    for table, column, coltype in MIGRATIONS:
        try:
            conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {coltype}")
        except sqlite3.OperationalError as e:
            if "duplicate column name" not in str(e):
                raise
    conn.commit()


def dedupe_opportunity_spaces(conn):
    dup_groups = conn.execute(
        "SELECT vertical, use_case, technology, MIN(id) AS keep_id, COUNT(*) AS c\n           FROM opportunity_spaces\n           GROUP BY vertical, use_case, technology\n           HAVING c > 1"
    ).fetchall()
    for g in dup_groups:
        losers = conn.execute(
            "SELECT id, label FROM opportunity_spaces\n               WHERE vertical = ? AND use_case = ? AND technology = ? AND id != ?",
            (g["vertical"], g["use_case"], g["technology"], g["keep_id"]),
        ).fetchall()
        for loser in losers:
            print(
                f"[dedupe_opportunity_spaces] removing duplicate {loser['label']} -- same triple ({g['vertical']} x {g['use_case']} x {g['technology']}) already registered under an earlier OS."
            )
            conn.execute(
                "DELETE FROM opportunity_signals WHERE opportunity_space_id = ?",
                (loser["id"],),
            )
            conn.execute(
                "DELETE FROM scores WHERE opportunity_space_id = ?", (loser["id"],)
            )
            conn.execute(
                "DELETE FROM right_to_win_scores WHERE opportunity_space_id = ?",
                (loser["id"],),
            )
            conn.execute("DELETE FROM opportunity_spaces WHERE id = ?", (loser["id"],))
    conn.commit()


def ensure_opportunity_space_uniqueness(conn):
    try:
        conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_opportunity_spaces_triple\n               ON opportunity_spaces (vertical, use_case, technology)"
        )
        conn.commit()
    except sqlite3.IntegrityError as e:
        print(
            f"[!] Could not enforce opportunity_spaces triple uniqueness -- duplicates still present: {e}"
        )


def init_db():
    conn = get_connection()
    conn.executescript(SCHEMA)
    for table in repair_foreign_key_targets(conn):
        print(f"[init_db] rebuilt {table}: its foreign keys named a table that no longer exists")
    migrate_schema(conn)
    dedupe_opportunity_spaces(conn)
    ensure_opportunity_space_uniqueness(conn)
    conn.commit()
    conn.close()


def new_run_id():
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def add_to_watchlist(conn, term, category, vertical=None):
    if not term:
        print(
            f"[add_to_watchlist] skipped -- empty/None term (category={category}, vertical={vertical})"
        )
        return
    now = datetime.now(timezone.utc).isoformat()
    existing = conn.execute(
        "SELECT id, frequency FROM watchlist_terms WHERE term = ? AND category = ? AND vertical IS ?",
        (term, category, vertical),
    ).fetchone()
    if existing:
        conn.execute(
            "UPDATE watchlist_terms SET frequency = frequency + 1, last_seen = ? WHERE id = ?",
            (now, existing["id"]),
        )
    else:
        conn.execute(
            "INSERT INTO watchlist_terms (term, category, vertical, frequency, first_seen, last_seen)\n               VALUES (?, ?, ?, 1, ?, ?)",
            (term, category, vertical, now, now),
        )
    conn.commit()


def list_watchlist(conn, min_frequency=None, status="pending"):
    query = "SELECT * FROM watchlist_terms WHERE status = ?"
    params = [status]
    if min_frequency is not None:
        query += " AND frequency >= ?"
        params.append(min_frequency)
    query += " ORDER BY frequency DESC"
    return conn.execute(query, params).fetchall()


def update_watchlist_status(conn, watchlist_id, status):
    conn.execute(
        "UPDATE watchlist_terms SET status = ? WHERE id = ?", (status, watchlist_id)
    )
    conn.commit()


def add_or_update_recurring_theme(
    conn,
    vertical,
    use_case,
    technology,
    rationale="",
    supporting_signal_count=0,
    run_id=None,
):
    now = datetime.now(timezone.utc).isoformat()
    existing = conn.execute(
        "SELECT id, frequency FROM recurring_themes WHERE vertical = ? AND use_case = ? AND technology = ?",
        (vertical, use_case, technology),
    ).fetchone()
    if existing:
        new_freq = existing["frequency"] + 1
        conn.execute(
            "UPDATE recurring_themes\n               SET frequency = ?, last_seen = ?, supporting_signal_count = ?, run_id = COALESCE(?, run_id)\n               WHERE id = ?",
            (new_freq, now, supporting_signal_count, run_id, existing["id"]),
        )
        conn.commit()
        return ("updated", new_freq)
    conn.execute(
        "INSERT INTO recurring_themes\n           (vertical, use_case, technology, rationale, supporting_signal_count,\n            first_seen, last_seen, frequency, promoted, run_id)\n           VALUES (?, ?, ?, ?, ?, ?, ?, 1, 0, ?)",
        (
            vertical,
            use_case,
            technology,
            rationale,
            supporting_signal_count,
            now,
            now,
            run_id,
        ),
    )
    conn.commit()
    return ("inserted", 1)


def list_promotable_themes(conn, min_frequency):
    return conn.execute(
        "SELECT * FROM recurring_themes WHERE frequency >= ? AND promoted = 0 ORDER BY frequency DESC",
        (min_frequency,),
    ).fetchall()


def mark_theme_promoted(conn, theme_id):
    conn.execute("UPDATE recurring_themes SET promoted = 1 WHERE id = ?", (theme_id,))
    conn.commit()


def insert_signal(
    conn,
    source_name,
    source_url,
    signal_type,
    title,
    summary=None,
    published_date=None,
    vertical_hint=None,
):
    try:
        conn.execute(
            "INSERT INTO signals\n               (source_name, source_url, signal_type, title, summary,\n                published_date, collected_at, vertical_hint)\n               VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (
                source_name,
                source_url,
                signal_type,
                title,
                summary,
                published_date,
                datetime.now(timezone.utc).isoformat(),
                vertical_hint,
            ),
        )
        conn.commit()
        return True
    except sqlite3.IntegrityError:
        return False


def get_signals_for_vertical(conn, vertical_hint, since_iso=None):
    unknown_vertical_placeholders = ",".join(("?" for _ in VERTICALS))
    query = f"SELECT * FROM signals WHERE (vertical_hint = ? OR vertical_hint IS NULL OR vertical_hint NOT IN ({unknown_vertical_placeholders}))"
    params = [vertical_hint] + list(VERTICALS)
    if since_iso:
        query += " AND collected_at >= ?"
        params.append(since_iso)
    return conn.execute(query, params).fetchall()


def get_linked_signals_for_opportunity_space(conn, opportunity_space_id):
    return conn.execute(
        "SELECT signals.* FROM signals\n           JOIN opportunity_signals ON signals.id = opportunity_signals.signal_id\n           WHERE opportunity_signals.opportunity_space_id = ?",
        (opportunity_space_id,),
    ).fetchall()


def update_opportunity_space_enrichment(
    conn,
    opportunity_space_id,
    role=None,
    buyer_persona=None,
    geography=None,
    horizon=None,
    domain=None,
    next_action=None,
    next_action_strategist=None,
    next_action_sales=None,
    next_action_presales=None,
):
    conn.execute(
        "UPDATE opportunity_spaces\n           SET persona = COALESCE(?, persona),\n               buyer_persona = COALESCE(?, buyer_persona),\n               geography = COALESCE(?, geography),\n               horizon = COALESCE(?, horizon),\n               domain = COALESCE(?, domain),\n               next_action = COALESCE(?, next_action),\n               next_action_strategist = COALESCE(?, next_action_strategist),\n               next_action_sales = COALESCE(?, next_action_sales),\n               next_action_presales = COALESCE(?, next_action_presales)\n           WHERE id = ?",
        (
            role,
            buyer_persona,
            geography,
            horizon,
            domain,
            next_action,
            next_action_strategist,
            next_action_sales,
            next_action_presales,
            opportunity_space_id,
        ),
    )
    conn.commit()


def find_opportunity_space_by_triple(
    conn, vertical, use_case, technology, exclude_label=None
):
    if exclude_label:
        return conn.execute(
            "SELECT * FROM opportunity_spaces WHERE vertical = ? AND use_case = ? AND technology = ? AND label != ?",
            (vertical, use_case, technology, exclude_label),
        ).fetchone()
    return conn.execute(
        "SELECT * FROM opportunity_spaces WHERE vertical = ? AND use_case = ? AND technology = ?",
        (vertical, use_case, technology),
    ).fetchone()


def next_opportunity_space_label(conn, prefix="OS", width=3):
    rows = conn.execute(
        "SELECT label FROM opportunity_spaces WHERE label LIKE ?", (f"{prefix}%",)
    ).fetchall()
    max_n = 0
    for r in rows:
        suffix = r["label"][len(prefix) :]
        if suffix.isdigit():
            max_n = max(max_n, int(suffix))
    return f"{prefix}{max_n + 1:0{width}d}"


def upsert_opportunity_space(conn, run_id, label, vertical, use_case, technology):
    now = datetime.now(timezone.utc).isoformat()
    existing = conn.execute(
        "SELECT id, vertical, use_case, technology FROM opportunity_spaces WHERE label = ?",
        (label,),
    ).fetchone()
    if existing:
        definition_changed = (
            existing["vertical"] != vertical
            or existing["use_case"] != use_case
            or existing["technology"] != technology
        )
        if definition_changed:
            conn.execute(
                "UPDATE opportunity_spaces\n                   SET run_id = ?, vertical = ?, use_case = ?, technology = ?, last_refreshed = ?,\n                       persona = NULL, buyer_persona = NULL, geography = NULL, horizon = NULL,\n                       domain = NULL, next_action = NULL, next_action_strategist = NULL,\n                       next_action_sales = NULL, next_action_presales = NULL\n                   WHERE id = ?",
                (run_id, vertical, use_case, technology, now, existing["id"]),
            )
        else:
            conn.execute(
                "UPDATE opportunity_spaces SET run_id = ?, last_refreshed = ? WHERE id = ?",
                (run_id, now, existing["id"]),
            )
        conn.commit()
        return existing["id"]
    cur = conn.execute(
        "INSERT INTO opportunity_spaces\n           (label, run_id, vertical, use_case, technology, created_at, last_refreshed)\n           VALUES (?, ?, ?, ?, ?, ?, ?)",
        (label, run_id, vertical, use_case, technology, now, now),
    )
    conn.commit()
    return cur.lastrowid


def get_latest_opportunity_spaces(conn):
    latest = conn.execute(
        "SELECT MAX(run_id) as latest FROM opportunity_spaces WHERE run_id IS NOT NULL"
    ).fetchone()["latest"]
    if latest is None:
        return conn.execute("SELECT * FROM opportunity_spaces").fetchall()
    return conn.execute(
        "SELECT * FROM opportunity_spaces WHERE run_id = ?", (latest,)
    ).fetchall()


def get_all_opportunity_spaces(conn):
    return conn.execute("SELECT * FROM opportunity_spaces ORDER BY label").fetchall()


def get_unscored_opportunity_spaces(conn):
    return conn.execute(
        "SELECT * FROM opportunity_spaces\n           WHERE id NOT IN (SELECT opportunity_space_id FROM scores)\n           ORDER BY label"
    ).fetchall()


def get_opportunity_spaces_missing_right_to_win(conn):
    return conn.execute(
        "SELECT * FROM opportunity_spaces\n           WHERE id IN (SELECT opportunity_space_id FROM scores)\n             AND id NOT IN (SELECT opportunity_space_id FROM right_to_win_scores)\n           ORDER BY label"
    ).fetchall()


def get_opportunity_spaces_with_fallback_scores(conn):
    return conn.execute(
        "SELECT os.* FROM opportunity_spaces os\n           JOIN scores s ON s.id = (\n               SELECT id FROM scores WHERE opportunity_space_id = os.id\n               ORDER BY computed_at DESC, id DESC LIMIT 1\n           )\n           JOIN right_to_win_scores r ON r.id = (\n               SELECT id FROM right_to_win_scores WHERE opportunity_space_id = os.id\n               ORDER BY computed_at DESC, id DESC LIMIT 1\n           )\n           WHERE s.evidence_quality_justification LIKE '%unavailable%'\n              OR s.strategic_relevance_justification LIKE '%unavailable%'\n              OR r.justification LIKE '%unavailable%'\n           ORDER BY os.label"
    ).fetchall()


def get_opportunity_spaces_with_old_scores(conn):
    return conn.execute(
        "SELECT * FROM opportunity_spaces\n           WHERE id IN (SELECT opportunity_space_id FROM scores WHERE datetime(computed_at) < datetime('now', '-3 days'))\n           ORDER BY label"
    ).fetchall()


def get_latest_scores(conn):
    return conn.execute(
        "\n        SELECT os.id, os.label, os.vertical, os.use_case, os.technology,\n               s.market_signal_strength, s.source_diversity, s.evidence_quality,\n               s.evidence_quality_justification, s.novelty_momentum,\n               s.strategic_relevance, s.strategic_relevance_justification,\n               s.urgency_score, s.total_score,\n               r.portfolio_distance, r.right_to_win_score, r.matched_assets, r.justification\n        FROM opportunity_spaces os\n        JOIN scores s ON s.id = (\n            SELECT id FROM scores WHERE opportunity_space_id = os.id\n            ORDER BY computed_at DESC, id DESC LIMIT 1\n        )\n        LEFT JOIN right_to_win_scores r ON r.id = (\n            SELECT id FROM right_to_win_scores WHERE opportunity_space_id = os.id\n            ORDER BY computed_at DESC, id DESC LIMIT 1\n        )\n        ORDER BY os.label\n    "
    ).fetchall()


def get_scores_ranked_by_persona_vertical(conn, persona=None, vertical=None):
    query = "\n        SELECT os.id, os.label, os.vertical, os.use_case, os.technology,\n               os.persona, os.buyer_persona, os.horizon, os.domain,\n               s.total_score, s.urgency_score,\n               r.portfolio_distance, r.right_to_win_score\n        FROM opportunity_spaces os\n        JOIN scores s ON s.id = (\n            SELECT id FROM scores WHERE opportunity_space_id = os.id\n            ORDER BY computed_at DESC, id DESC LIMIT 1\n        )\n        LEFT JOIN right_to_win_scores r ON r.id = (\n            SELECT id FROM right_to_win_scores WHERE opportunity_space_id = os.id\n            ORDER BY computed_at DESC, id DESC LIMIT 1\n        )\n        WHERE 1=1\n    "
    params = []
    if persona:
        query += " AND os.persona = ?"
        params.append(persona)
    if vertical:
        query += " AND os.vertical = ?"
        params.append(vertical)
    query += "\n        ORDER BY (os.persona IS NULL), os.persona, os.vertical, s.total_score DESC\n    "
    return conn.execute(query, params).fetchall()


def link_signal_to_opportunity(conn, opportunity_space_id, signal_id):
    conn.execute(
        "INSERT OR IGNORE INTO opportunity_signals (opportunity_space_id, signal_id)\n           VALUES (?, ?)",
        (opportunity_space_id, signal_id),
    )
    conn.commit()


# Substring carried by every degraded justification scoring.py writes (it
# imports this name, so there is one definition). Both insert functions below
# use it to refuse a write that would bury a real score, and
# get_opportunity_spaces_with_fallback_scores() repeats it as a SQL LIKE
# pattern to find the rows worth rescuing -- keep the two in step.
FALLBACK_MARKER = "unavailable"


def _is_fallback(justification) -> bool:
    """True if a justification marks its score as a neutral placeholder."""
    return bool(justification) and FALLBACK_MARKER in str(justification).lower()


def insert_score(
    conn,
    opportunity_space_id,
    sub_scores: dict,
    total_score: float,
    evidence_quality_justification=None,
    strategic_relevance_justification=None,
    urgency_score=None,
) -> bool:
    """Write (or update) the attractiveness score of one opportunity space.

    Returns True if the row was written, False if the write was refused because
    it would have replaced a real score with a fallback. That refusal matters:
    when no LLM provider answers, the callers hand us a neutral 5.0 with an
    "unavailable" justification, and a `--force` rescore used to silently
    overwrite a good score with it. A fallback may only land on an empty row or
    on another fallback; the whole row is kept or dropped together, since the
    deterministic sub-scores alone cannot be mixed with a stale LLM half.
    """
    existing = conn.execute(
        "SELECT evidence_quality_justification, strategic_relevance_justification\n           FROM scores WHERE opportunity_space_id = ?",
        (opportunity_space_id,),
    ).fetchone()
    existing_os = 1 if existing else 0
    if existing_os > 0:
        incoming_is_fallback = _is_fallback(
            evidence_quality_justification
        ) or _is_fallback(strategic_relevance_justification)
        stored_is_fallback = _is_fallback(
            existing["evidence_quality_justification"]
        ) or _is_fallback(existing["strategic_relevance_justification"])
        if incoming_is_fallback and (not stored_is_fallback):
            return False
        conn.execute(
            "\n            UPDATE scores\n            SET\n                market_signal_strength = ?,\n                source_diversity = ?,\n                evidence_quality = ?,\n                evidence_quality_justification = ?,\n                novelty_momentum = ?,\n                strategic_relevance = ?,\n                strategic_relevance_justification = ?,\n                urgency_score = ?,\n                total_score = ?,\n                computed_at = ?\n            WHERE opportunity_space_id = ?\n            ",
            (
                sub_scores.get("market_signal_strength"),
                sub_scores.get("source_diversity"),
                sub_scores.get("evidence_quality"),
                evidence_quality_justification,
                sub_scores.get("novelty_momentum"),
                sub_scores.get("strategic_relevance"),
                strategic_relevance_justification,
                urgency_score,
                total_score,
                datetime.now(timezone.utc).isoformat(),
                opportunity_space_id,
            ),
        )
    else:
        conn.execute(
            "\n            INSERT INTO scores\n            (\n                opportunity_space_id,\n                market_signal_strength,\n                source_diversity,\n                evidence_quality,\n                evidence_quality_justification,\n                novelty_momentum,\n                strategic_relevance,\n                strategic_relevance_justification,\n                urgency_score,\n                total_score,\n                computed_at\n            )\n            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\n            ",
            (
                opportunity_space_id,
                sub_scores.get("market_signal_strength"),
                sub_scores.get("source_diversity"),
                sub_scores.get("evidence_quality"),
                evidence_quality_justification,
                sub_scores.get("novelty_momentum"),
                sub_scores.get("strategic_relevance"),
                strategic_relevance_justification,
                urgency_score,
                total_score,
                datetime.now(timezone.utc).isoformat(),
            ),
        )
    conn.commit()
    return True


def insert_right_to_win_score(
    conn,
    opportunity_space_id,
    portfolio_distance,
    right_to_win_score: float,
    matched_assets,
    justification,
) -> bool:
    """Write (or update) the right-to-win score of one opportunity space.

    Returns True if the row was written, False if the write was refused for the
    same reason as insert_score(): when no provider answers, the caller hands us
    L4 / 0.0 with an "unavailable" justification, and overwriting a real
    classification with that is worse than keeping yesterday's number.
    """
    existing_rtw_row = conn.execute(
        "SELECT justification FROM right_to_win_scores WHERE opportunity_space_id = ?",
        (opportunity_space_id,),
    ).fetchone()
    existing_rtw = 1 if existing_rtw_row else 0
    if existing_rtw > 0:
        if _is_fallback(justification) and (
            not _is_fallback(existing_rtw_row["justification"])
        ):
            return False
        conn.execute(
            "\n            UPDATE right_to_win_scores\n            SET\n                portfolio_distance = ?,\n                right_to_win_score = ?,\n                matched_assets = ?,\n                justification = ?,\n                computed_at = ?\n            WHERE opportunity_space_id = ?\n            ",
            (
                portfolio_distance,
                right_to_win_score,
                matched_assets,
                justification,
                datetime.now(timezone.utc).isoformat(),
                opportunity_space_id,
            ),
        )
    else:
        conn.execute(
            "INSERT INTO right_to_win_scores\n            (opportunity_space_id, portfolio_distance, right_to_win_score,\n                matched_assets, justification, computed_at)\n            VALUES (?, ?, ?, ?, ?, ?)",
            (
                opportunity_space_id,
                portfolio_distance,
                right_to_win_score,
                matched_assets,
                justification,
                datetime.now(timezone.utc).isoformat(),
            ),
        )
    conn.commit()
    return True


def delete_opportunity_spaces(conn, labels):
    deleted = []
    for label in labels:
        row = conn.execute(
            "SELECT id FROM opportunity_spaces WHERE label = ?", (label,)
        ).fetchone()
        if not row:
            continue
        os_id = row["id"]
        conn.execute(
            "DELETE FROM opportunity_signals WHERE opportunity_space_id = ?", (os_id,)
        )
        conn.execute("DELETE FROM scores WHERE opportunity_space_id = ?", (os_id,))
        conn.execute(
            "DELETE FROM right_to_win_scores WHERE opportunity_space_id = ?", (os_id,)
        )
        conn.execute("DELETE FROM opportunity_spaces WHERE id = ?", (os_id,))
        deleted.append(label)
    conn.commit()
    return deleted


def wipe_opportunity_spaces(conn):
    conn.execute("DELETE FROM opportunity_signals")
    conn.execute("DELETE FROM scores")
    conn.execute("DELETE FROM right_to_win_scores")
    conn.execute("DELETE FROM opportunity_spaces")
    for table in (
        "opportunity_signals",
        "scores",
        "right_to_win_scores",
        "opportunity_spaces",
    ):
        try:
            conn.execute("DELETE FROM sqlite_sequence WHERE name = ?", (table,))
        except sqlite3.OperationalError:
            pass
    conn.commit()


if __name__ == "__main__":
    init_db()
    print(f"Database initialized at {DB_PATH}")